version: "3.7"
services:
  mariadb:
    image: "mariadb:10.5"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "appointment"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data:
